defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *defaults
  database: parapets_dev

test:
  <<: *defaults
  database: parapets_test

production:
  <<: *defaults
  database: parapets
